version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: poetry config settings.virtualenvs.in-project true
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: poetry install
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          command: |
            poetry run pytest --cov-report=xml --cov-report=xml --cov=testproj
  deploy:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - add_ssh_keys
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: pip install -i https://test.pypi.org/simple/ --pre autopub
      - run: autopub check
      - run: pip install githubrelease
      - run: autopub prepare
      - run: poetry build
      - run: autopub commit
      - run: autopub githubrelease
      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: poetry publish -r testpypi -u $PYPI_USERNAME -p $PYPI_PASSWORD


workflows:
  version: 2
  main:
    jobs:
      - test
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
